### ISSUE TITLE
Problem 1.4.5

### ISSUE THREAD

**Issue by MateuszOlko** [lclem/logic_course#12]
There is a mistake in second solution.
Sentence "Since rho|=phi(p3, p4) by definition of Delta(G), phi is satisfied when both its arguments are set to rho(p2)" is not true or at least is not proven in the solution.
However, if we change rho(p2) to ~rho(p2)(negate) then it is easily provable and presented reasoning makes sense (since rho(p2) != rho(p3) implies rho(p2) = ~rho(p3)).
Consequently, negation should be applied to rho(p2) in the next sentence of the solution.

**Comment by lclem** [comment]
you are right, the last two occurrences of $rho(p2)$ should be replaced by $1 - rho(p2)$.
