### ISSUE TITLE
Problem 1.1.7 first solution

### ISSUE THREAD

**Issue by aswietlik** [lclem/logic_course#14]
It says "By definition, ∆ ⊧ ϕ if, for every valuation s.t. ⟦ψ⟧ = 1 for every ψ ∈ ∆, we have ⟦ϕ⟧ = 1 as well. Replacing ∆ with a larger set of formulas Γ results in a **smaller set of such ψ’s**, and thus Γ ⊧ ϕ follows" 

It gives us a larger set of ψ, hence smaller set of valuations that satisfy them.

**Comment by lclem** [comment]
you are completely right, the bold occurrence of ψ should be replace by the valuation \varrho. thanks!
