### ISSUE TITLE
Problem 2.8.17

### ISSUE THREAD

**Issue by aswietlik** [lclem/logic_course#16]
There's a missing closing bracket:
ψ ≡ [ϕ]U ∧ ∀x . **f(f(x)** = x ∧ f(x) ≠ x ∧ (U(x) ↔ ¬U(f(x)))
should be:
ψ ≡ [ϕ]U ∧ ∀x . **f(f(x))** = x ∧ f(x) ≠ x ∧ (U(x) ↔ ¬U(f(x)))

**Comment by lclem** [comment]
agree, thanks for reporting!
