### ISSUE TITLE
Ambiguity in problem 2.1.9

### ISSUE THREAD

**Issue by vonknio** [lclem/logic_course#17]
Problem 2.1.9 asks to define a complete binary tree, but the solution provided defines a perfect (full and complete) binary tree. Actually according to [Wikipedia](https://en.wikipedia.org/wiki/Binary_tree#Types_of_binary_trees) there's some ambiguity as to what a complete binary tree is, but I believe the first interpretation is the most common one, so it would be a good idea to specify the definition in the problem statement.

**Comment by lclem** [comment]
thanks for pointing that out, we will clarify it!
