### ISSUE TITLE
Problem 2.3.1

### ISSUE THREAD

**Issue by vonknio** [lclem/logic_course#18]
I'm not sure if it's just me having trouble parsing it, but the statement of problem 2.3.1 says,

> In which structures is the following formula of one free variable φ(x) ≡ ∃y . y ≠ x x satisfied? 

The last occurrence of `x` seems odd. Should it be

> In which structures is the following formula of one free variable x φ(x) ≡ ∃y . y ≠ x satisfied? 

instead?

**Comment by lclem** [comment]
indeed, something strange happened there, thanks for reporting!
