### ISSUE TITLE
Solution 2.8.13 "Regarding 1)"

### ISSUE THREAD

**Issue by pieniacy** [lclem/logic_course#19]
In introducing relation E, in the second sentence I think there is a mistake that (as of now) leads to E being always empty:

`∀x∀y!∃yˆ . y ≈ yˆ ∧ E(x, yˆ)`

I read it: For arbitrary `x` and `y` there is no element in the same `≈` class with `y` that is in relation `E` with `x`, hence no `≈` class has any `E` connections with this `x`, hence this `x` has no connections in `E`, hence `E` is empty.

I believe this can be fixed by replacing that last sentence with those 2:
`∀x∀y∃z . z ≈ y ∧ E(x, z)` [every `x` is in `E` with some `z` from every `≈` class]
`∀x∀y . E(x, y) → (∀z . z ≈ y ∧ E(x, z) → z = y)` [every `x` is in `E` with at most one element from every `≈` class]

**Comment by lclem** [comment]
it was a spelling error, the formula should have been "∀x∀y∃!yˆ . y ≈ yˆ ∧ E(x, yˆ)"
where "∃!" means "exists unique". is it more clear now?

**Comment by pieniacy** [comment]
yep, it works as well

**Comment by lclem** [comment]
great, thanks for reporting this issue!
