### ISSUE TITLE
Problems with Problem 1.2.3.5

### ISSUE THREAD

**Issue by m-chrzan** [lclem/logic_course#2]
The [Sheffer stroke](https://en.wikipedia.org/wiki/Sheffer_stroke) up-arrow is traditionally (as mentioned in the text) used for the NAND function, which is a negated conjunction. The problem statement defines it as a conjunction of negations, which is the NOR function.

In the solution, it is stated that `p ↑ p ≡ ⊥` which is not true (for either NAND or NOR) when `p`'s value is 0. Instead, `φ ↑ φ ≡ ¬φ` is true, which we can use to solve the problem.

**Comment by lclem** [comment]
you are right, thanks!
