### ISSUE TITLE
Proof of P4.2.4 (in the 05-24 version) 

### ISSUE THREAD

**Issue by jacekchrzaszcz** [lclem/logic_course#32]
The formula at the end of the proof is way too simple, and wrong: there are i_s under z's and j_s on the right. Besides I guess you need to consider permutations of indices of z's...

**Comment by lclem** [comment]
thanks for spotting this! I agree that the i's should be j's instead.
regarding permutations, I'm not sure. do you have a minimal counter-example?

**Comment by jacekchrzaszcz** [comment]
OK, forget the permutations :) The formula I was thinking about was much more complicated than yours. I thought about forming groups from z_i's and saying that z_i's from different groups should be \neq - and for that permutations would be needed. Your formula - select n vars, say that they must me pairwise disjoint and ignore the rest - is of course much simpler.
