### ISSUE TITLE
Exercise 5.3.2

### ISSUE THREAD

**Issue by jedrzejKolodziejski** [lclem/logic_course#4]
Exercise 5.3.2 (and its solution) is stated in a wrong form.

It is not true in general that you can encode WMSO in FO if your signature is "+" and "*" (even if you assume PA axioms, or the full FO theory of (N,+,*)). Such a translation becomes possible if you only consider equivalence in the standard model - and perhaps this was the intended meaning of the exercise (as then the solution works).

**Comment by J-Ty** [comment]
Yes, you are 100% right. The correct form concerns only the standard model of arithmetic. It somehow got lost in the process of converting from the Polish [smurf variant](http://smurf.mimuw.edu.pl/node/1809) to the present form.
