### ISSUE TITLE
P2.12.6 solution

### ISSUE THREAD

**Issue by pieniacy** [lclem/logic_course#41]
There might be problems with 2.12.6 solution.

Firstly, in every `n` occurence in solution in formulas like `2^n...` I think it should be `k` instead, because at the beginning of the solution that is our round count and as I understand it was the idea behind that `n`.

Bigger problem is I think the solution is incomplete, I think there is a problem with new maximal element: with what is already in the solution we would never exit `B1`, because there is a mechanism for a new maximal element when Player1 chooses in `A`, but not when she chooses in `B`. But only way for us to have any `b` in `B2` is for Player1 to play new maximum element in `B2` and that mechanism is not covered in the solution. There is a mention at the end of solution:

_The argument if Player I plays bm+1 ∈ B is similar._

But it is not similar with a new maximum element thats played in `B2` by Player1, because its distance from previous maximum (which is in `B1`) is infinity, so Player2 cannot choose in `A` while preserving distance.

**Comment by lclem** [comment]
you are right, the solution was already quite long and the details of when P I plays in B where omitted.

I will add just a comment regarding the new case when P I plays a new maximal element b_{m+1} in B2 s.t. the previous maximal element $b_i$ is in B1: In that case, P II selects any element $a_{m+1}$ in N s.t. the distance from $a_i$ is at least $2^{n-(m+1)+1$.
